name: build-and-deploy

on:
  push:
    branches: [master]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Save repo name in environment variable
        run: |
          echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
          echo "$REPOSITORY_NAME"
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "$REPOSITORY_NAME"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
